Added retrial of unzip (in emftp) and lftp (in radftp) in case of errors (may due to replacement of the file beinf downloaded)

diff --git a/tools/emftp/emftp.sh.in b/tools/emftp/emftp.sh.in
--- a/tools/emftp/emftp.sh.in
+++ b/tools/emftp/emftp.sh.in
@@ -345,23 +345,38 @@ trap cleanup HUP INT QUIT ABRT KILL ALRM TERM EXIT
 
 log_msg "emftp script starting"
 
-errmsg=`curl -s -S -o ${ginputfpath} -m 20 --retry 1 ${gurl}/${ginputfilename} \
-2>&1`
-[ $? -ne 0 ] && { log_err_quit "Error from curl: $errmsg"; }
+count=0
+while [ $count -le 2 ]
+do
+    count=`expr $count + 1`
+    errmsg=`curl -s -S -o ${ginputfpath} -m 20 --retry 1 \
+    		 ${gurl}/${ginputfilename} 2>&1`
+    [ $? -ne 0 ] && { log_err_quit "Error from curl: $errmsg"; }
 
-oldmd5key=
-[ -f $gmd5keyfpath ] && { oldmd5key=`cat $gmd5keyfpath`; }
-# [ -f $ginvfpath ] && { oldmd5key=`tail -n 1 ${ginvfpath} | cut -f 2 -d ' '`; }
-md5key=`openssl md5 ${ginputfpath} | cut -f 2 -d ' '` 
+    oldmd5key=
+    [ -f $gmd5keyfpath ] && { oldmd5key=`cat $gmd5keyfpath`; }
+    # [ -f $ginvfpath ] && \
+    #    { oldmd5key=`tail -n 1 ${ginvfpath} | cut -f 2 -d ' '`; }
+    md5key=`openssl md5 ${ginputfpath} | cut -f 2 -d ' '` 
 
-if [ $md5key = "$oldmd5key" ]
-then
-    rm $ginputfpath
-    log_msg_quit "Not a new file"
-fi
+    if [ $md5key = "$oldmd5key" ]
+    then
+	rm $ginputfpath
+	log_msg_quit "Not a new file"
+    fi
 
-errmsg=`unzip -d $gtmpdir $ginputfpath 2>&1`
-[ $? -ne 0 ] && { log_err_quit "Error unziping $ginputfpath: $errmsg"; }
+    errmsg=`unzip -d $gtmpdir $ginputfpath 2>&1`
+    if [ $? -eq 0 ]
+    then
+	status=0
+	break
+    else
+	status=1
+	log_err "Error unziping $ginputfpath: $errmsg"
+    fi
+done
+
+[ $status -ne 0 ] && { log_err_quit "Retrying unzip exhausted"; }
 
 # Some files are sent compressed (.zip). The npemwin qrunner will
 # accept those and handle them. But nbsp expects the txt uncompressed files.
diff --git a/tools/radftp/radftp.sh.in b/tools/radftp/radftp.sh.in
--- a/tools/radftp/radftp.sh.in
+++ b/tools/radftp/radftp.sh.in
@@ -239,13 +239,24 @@ do
 done
 echo "exit" >> $glftprcpath
 
-# exec lftp
-errmsg=`lftp -f $glftprcpath 2>&1`
-if [ $? -ne 0 ]
-then
-    log_err_quit "Error from lftp: $errmsg"
-fi
-   
+# exec lftp (with retry)
+count=0
+while [ $count -le 2 ]
+do
+    count=`expr $count + 1`
+    errmsg=`lftp -f $glftprcpath 2>&1`
+    if [ $? -eq 0 ]
+    then
+        status=0
+	break
+    else
+        status=1	
+        log_err "Error from lftp: $errmsg"
+    fi
+done
+
+[ $status -ne 0 ] && { log_err_quit "Retrying lftp exhausted"; }
+
 # npemwin and nbsp processing
 grep -v '^#\|^$' $gradftpslist | while read station
 do
