Revised cleanup() in emftp and the log_err function

diff --git a/tools/emftp/emftp.sh.in b/tools/emftp/emftp.sh.in
--- a/tools/emftp/emftp.sh.in
+++ b/tools/emftp/emftp.sh.in
@@ -61,17 +61,22 @@ log_msg_quit(){
 log_err(){
 
     log_msg "$1"
+}
+
+log_err_quit(){
+
+    log_msg "$1"
     exit 1
 }
 
 cleanup(){
+    
+    rm -f $ginputfpath
+    rm -f $gtmpdir/*
 
     unlock_dir $glockdirpath
     log_msg "emftp script finished"
-
-    exit 0
 }
-
 
 lock_dir(){
 
@@ -93,7 +98,7 @@ lock_dir(){
 
     if [ $status -ne 0 ]
     then
-	log_err "Cannot lock $lockdir"
+	log_err_quit "Cannot lock $lockdir"
     fi
 }
 
@@ -192,7 +197,7 @@ sanity_check(){
     for _d in inputs spool inv lock tmp
     do
 	eval _dir=\$g${_d}dir
-	[ ! -d ${_dir} ] && { log_err "${_dir} does not exist"; }
+	[ ! -d ${_dir} ] && { log_err_quit "${_dir} does not exist"; }
     done
 }
 
@@ -337,8 +342,8 @@ trap cleanup HUP INT QUIT ABRT KILL ALRM TERM EXIT
 
 log_msg "emftp script starting"
 
-curl -s -o ${ginputfpath} -m 20 ${gurl}/${ginputfilename}
-[ $? -ne 0 ] && { log_err "Error from curl"; }
+curl -s -o ${ginputfpath} -m 20 --retry 1 ${gurl}/${ginputfilename}
+[ $? -ne 0 ] && { log_err_quit "Error from curl"; }
 
 oldmd5key=
 [ -f $gmd5keyfpath ] && { oldmd5key=`cat $gmd5keyfpath`; }
@@ -352,7 +357,7 @@ then
 fi
 
 unzip -d $gtmpdir $ginputfpath > /dev/null 2>&1
-[ $? -ne 0 ] && { log_err "Error unziping $ginputfpath"; }
+[ $? -ne 0 ] && { log_err_quit "Error unziping $ginputfpath"; }
 
 # Some files are sent compressed (.zip). The npemwin qrunner will
 # accept those and handle them. But nbsp expects the txt uncompressed files.
@@ -378,7 +383,7 @@ do
     number_parts=`get_number_parts $f`
     if [ $number_parts -ne 6 ]
     then
-	log_msg "Invalid file name: unexpected number of parts: $f"
+	log_err "Invalid file name: unexpected number of parts: $f"
 	rm $f
 	continue
     fi
@@ -416,7 +421,7 @@ do
 	_status=$?
 	if [ ${_status} -ne 0 ]
 	then
-	    log_msg "Error from npemwininsert processing $emfpath"
+	    log_err "Error from npemwininsert processing $emfpath"
 	fi
     fi
 
@@ -426,7 +431,7 @@ do
 	_status=$?
 	if [ ${_status} -ne 0 ]
 	then
-	    log_msg "Error from nbspmcast processing $emfpath"
+	    log_err "Error from nbspmcast processing $emfpath"
 	fi
     fi
 
@@ -443,5 +448,3 @@ done
 
 echo $md5key > ${gmd5keyfpath}
 [ $gwrite_inv -eq 1 ] && { echo "$gtime $md5key" >> $ginvfpath; }
-
-rm $ginputfpath
